# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
r: bioc

cache: packages

# Bioconductor
bioc_required: true
bioc_check: true

r_packages:
  - rmarkdown
  - BiocManager
  - covr

# On CRAN all warnings are treated as errors; this is not true on Bioconductor.
warnings_are_errors: false

before_script:
  # ensure bioc-devel is being used
  - R -e 'BiocManager::install(version = "devel", ask=FALSE)'
  - R -e 'BiocManager::valid()'

after_success:
  - Rscript -e 'covr::codecov()'

# Install Java 8 for RCDK
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
#  
#before_install:
#  - jdk_switcher use oraclejdk8
#  - java -version
